name: stadtnavi_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  back_button_interceptor: ^8.0.4
  dio: ^5.8.0+1
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  flutter_html: ^3.0.0
  trufi_core: 
    path: ../trufi-core
  flutter_map_marker_cluster: ^1.4.0
  graphql: ^5.2.1
  gtfs_realtime_bindings: ^1.1.0
  maps_toolkit: ^3.1.0
  matomo_tracker: ^6.0.0
  mqtt_client: ^10.8.1
  rive: ^0.13.20
  skeletonizer: ^2.0.1
  vector_tile: ^2.0.1
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
