version: '3'
services:
  nginx_single_server:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/logs/:/var/log/nginx
      - ./data/static_files:/app/static_files
      - ./data/well-known:/app/well-known
    command: nginx -g "daemon off;"
    restart: unless-stopped

networks:
  default:
    name: trufi-server
